name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        git submodule update --init --recursive
        make
    - name: make check
      run: |
        rm main.o
        make check
